# file: deploy-nginx.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: Configure-Jenkins-Integration
spec:
  description: Basic nginx deploy to k8s 
  application: &app-name armory-samples
  stages:
    - type: manualJudgment
      properties:
        name: Slack Chat Ops Approval
        refId: "1"
        failPipeline: true
        instructions: "Click Here ->  <a href=http://a594ebf7154144c8b840a5004b8ed253-1521180453.us-west-2.elb.amazonaws.com/productpage>Test App</a>   ---  Refresh App to See Change! <p><b>Select DropDown Option click \"Continue\"</b></p>"
